### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by DEAM0**

### CODE REVIEW

**Comment by belomaxorka** [comment]
Hello, what does the change bring?

**Comment by belomaxorka** [comment]
^8.0 == 8.0, 8.1, 8.2 and more...

**Comment by DEAM0** [comment]
I changed it because composer has a problem with php 8.2

**Comment by DEAM0** [comment]
I changed it because composer has a problem with php 8.2

**Comment by belomaxorka** [comment]
Can you show me the problem?

**Comment by belomaxorka** [comment]
PHP 8.2 currently has not full support in the project

**Comment by belomaxorka** [comment]
It will be implemented in the future

**Pull request closed without merging**
